version: '3.8'

services:
  app:
    build: .
    container_name: productservice
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ESTABLISHMENT_SERVICE_URL=${ESTABLISHMENT_SERVICE_URL}
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: postgres:16-alpine
    container_name: product-db
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network
volumes:
  postgres_data:
  
networks:
  shared-network:
    external: true
