
services:
  app:
    build: .
    container_name: establishmentservice
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: postgres:16-alpine
    container_name: establishment-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network
  
volumes:
  postgres_data: 
  
networks:
  shared-network:
    external: true